# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Login to Azure Container Registry
      inputs:
        command: login
        containerRegistry: 'ajudadeus-docker-connection'  # Nome da nova service connection

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/main/docker/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        containerRegistry: 'ajudadeus-docker-connection'  # Nome da nova service connection
        imageName: 'ajudadeus.azurecr.io/alerta_cidadao:$(tag)'  # Nome do seu ACR
